export enum ActivityType {
  EDUCATION = "EDUCATION",
  HACKATHON = "HACKATHON",
  NETWORKING = "NETWORKING",
  SOCIAL = "SOCIAL",
  UGHHEUNGCON = "UGHHEUNGCON",
  // WINTERPROJECT = "WINTERPROJECT",
  MENTORING = "MENTORING"
}
